### ISSUE TITLE
Imported file as Text is giving issues

### ISSUE THREAD

**Issue by PierreR** [vmchale/shake-dhall#1]
I have a weird issue with imported file.

Given this input:
```
let k8s =
      https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/master/package.dhall

let test =
      k8s.ConfigMap::{
      , metadata = k8s.ObjectMeta::{ name = Some "test" }
      , data = Some (toMap { foo = ./foo.conf as Text })
      }

in  test
```
Together with this foo.conf:

```
Here is the content of foo
```
I will produce the expected output with `dhall-to-yaml` or `shake`:

```
apiVersion: v1
data:
  foo: Here is the content of foo
kind: ConfigMap
metadata:
  name: test
```

But now if I add a line in 'foo.conf' such as `12s`:

```
Here is the content of foo
12s
```
The `dhall-to-yaml` is still producing the expected result but shake will give:
```
openshift/examples/foo.conf:2:3:
  |
2 | 12s
  |   ^
unexpected 's'
expecting ->, :, digit, end of input, operator, or whitespace
```

Please note that if I insert `&` in the file, I also get the error.

Any idea ?

**Comment by vmchale** [comment]
I think it's a bug in my code; I didn't check which files are Dhall code.

Hopefully have a fix up soon!

**Comment by vmchale** [comment]
Thanks for the bug report!

**Comment by PierreR** [comment]
It works nicely. Thanks for the quick fix.
